name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  build-on-windows:
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Build
        run: |
          cd Common.BasicHelper
          dotnet build -c Release

  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Build
        run: |
          cd Common.BasicHelper
          dotnet build -c Release

      - name: Add to GitHub Repo
        run: |
          nuget sources add -name github -Source https://nuget.pkg.github.com/Crequency/index.json -Username Crequency -Password ${{ secrets.GitHubToken }}

      - name: Install NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'

      - name: Publish Package to GitHub and NuGet
        run: |
          nuget push ./Common.BasicHelper/bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
          nuget push ./Common.BasicHelper/bin/Release/*.nupkg -Source github -SkipDuplicate


  build-on-macos:
    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Build
        run: |
          cd Common.BasicHelper
          dotnet build -c Release


