name: Publish

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

    workflow_dispatch:

jobs:
    build-on-ubuntu:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: |
                      8.0.x

            - name: Add to GitHub Repo
              if: ${{ github.event_name != 'pull_request' }}
              run: |
                  nuget sources add -name github -Source https://nuget.pkg.github.com/Crequency/index.json -Username Crequency -Password ${{ secrets.GitHubToken }}

            - name: Install NuGet
              uses: nuget/setup-nuget@v1
              if: ${{ github.event_name != 'pull_request' }}
              with:
                  nuget-version: "6.x"

            - name: Build and Publish Cli Tool
              working-directory: "Common.BasicHelper.Cli"
              if: ${{ github.event_name != 'pull_request' }}
              run: |
                  dotnet build -c Release

                  nuget push ./bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
                  nuget push ./bin/Release/*.nupkg -Source github -SkipDuplicate
